#Mod by void

[configs]
DisableOnSAMP = 0 #Automatically disable itself when playing SAMP. Default 0

EnableSlowMotion = 1 #Enable slow motion effect. Default 1
SlowMotionSpeed = 0.25 #How much the game slowdown when weapon wheel is opened (Dont affect SAMP). Default 0.25

PrimaryKey = 9 #First key to open the weapon wheel. Default 9 (TAB)
SecondaryKey = 81 #Second key to open the weapon wheel, if you only want to use one key, put the same as above. Default 81 (Q)
DetonatorKey = 69 #Key to alternate between explosive and detonator, is also the hotkey to it. Default = 69 (E)

OpenWheelWithScroll = 1 #This let you navigate through the weapon wheel using the mouse scroll. Default = 1
SlowMotionWithScroll = 0 #Will apply slowmotion effect when selecting weapons with the scroll. Default = 0

DeselectTimeMouse = 1200 #How much time will take to deselect the weapon slot after stop moving the mouse. Default = 1200
DeselectTimeScroll = 450 #How much time will take to close weapon wheel when using the scroll. Default = 450
DeselectTimeController = 1000 #How much time will take to deselect the weapon slot after release the analog stick. Default = 1000

DetailR = 159 #The red color of the detail that appears on the selected slot. Default 159
DetailG = 207 #The green color of the detail that appears on the selected slot. Default 207
DetailB = 114 #The blue color of the detail that appears on the selected slot. Default 114
DetailAnimSpeed = 2.0 #How fast the detail animation will happen. Default 2.0

SkipEmptySlots = 1 #Will ignore empty slots and select the next or closest occupied one. Default = 1
AmmoCounterLimit = 1 #Hide ammo counter when ammo is equal or higher than 10000. Default = 1
FlamethrowerAmmoFix = 1 #Shows flamethrower ammo with two digits the same way as in the default game interface. Default = 1
InvertScrollDirection = 0 #Invert the direction of the scroll. Default = 0
SetNextWeaponOnScroll = 1 #Will auto select the next weapon when scrolling, disabling it will just open the interface. Default = 1